namespace ProjectEulerSolutions.P42

abbrev wordsText : String :=
  "A,ABILITY,ABLE,ABOUT,ABOVE,ABSENCE,ABSOLUTELY,ACADEMIC,ACCEPT,ACCESS,ACCIDENT,ACCOMPANY,ACCORDING,ACCOUNT,ACHIEVE,ACHIEV" ++
  "EMENT,ACID,ACQUIRE,ACROSS,ACT,ACTION,ACTIVE,ACTIVITY,ACTUAL,ACTUALLY,ADD,ADDITION,ADDITIONAL,ADDRESS,ADMINISTRATION,ADMI" ++
  "T,ADOPT,ADULT,ADVANCE,ADVANTAGE,ADVICE,ADVISE,AFFAIR,AFFECT,AFFORD,AFRAID,AFTER,AFTERNOON,AFTERWARDS,AGAIN,AGAINST,AGE,A" ++
  "GENCY,AGENT,AGO,AGREE,AGREEMENT,AHEAD,AID,AIM,AIR,AIRCRAFT,ALL,ALLOW,ALMOST,ALONE,ALONG,ALREADY,ALRIGHT,ALSO,ALTERNATIVE" ++
  ",ALTHOUGH,ALWAYS,AMONG,AMONGST,AMOUNT,AN,ANALYSIS,ANCIENT,AND,ANIMAL,ANNOUNCE,ANNUAL,ANOTHER,ANSWER,ANY,ANYBODY,ANYONE,A" ++
  "NYTHING,ANYWAY,APART,APPARENT,APPARENTLY,APPEAL,APPEAR,APPEARANCE,APPLICATION,APPLY,APPOINT,APPOINTMENT,APPROACH,APPROPR" ++
  "IATE,APPROVE,AREA,ARGUE,ARGUMENT,ARISE,ARM,ARMY,AROUND,ARRANGE,ARRANGEMENT,ARRIVE,ART,ARTICLE,ARTIST,AS,ASK,ASPECT,ASSEM" ++
  "BLY,ASSESS,ASSESSMENT,ASSET,ASSOCIATE,ASSOCIATION,ASSUME,ASSUMPTION,AT,ATMOSPHERE,ATTACH,ATTACK,ATTEMPT,ATTEND,ATTENTION" ++
  ",ATTITUDE,ATTRACT,ATTRACTIVE,AUDIENCE,AUTHOR,AUTHORITY,AVAILABLE,AVERAGE,AVOID,AWARD,AWARE,AWAY,AYE,BABY,BACK,BACKGROUND" ++
  ",BAD,BAG,BALANCE,BALL,BAND,BANK,BAR,BASE,BASIC,BASIS,BATTLE,BE,BEAR,BEAT,BEAUTIFUL,BECAUSE,BECOME,BED,BEDROOM,BEFORE,BEG" ++
  "IN,BEGINNING,BEHAVIOUR,BEHIND,BELIEF,BELIEVE,BELONG,BELOW,BENEATH,BENEFIT,BESIDE,BEST,BETTER,BETWEEN,BEYOND,BIG,BILL,BIN" ++
  "D,BIRD,BIRTH,BIT,BLACK,BLOCK,BLOOD,BLOODY,BLOW,BLUE,BOARD,BOAT,BODY,BONE,BOOK,BORDER,BOTH,BOTTLE,BOTTOM,BOX,BOY,BRAIN,BR" ++
  "ANCH,BREAK,BREATH,BRIDGE,BRIEF,BRIGHT,BRING,BROAD,BROTHER,BUDGET,BUILD,BUILDING,BURN,BUS,BUSINESS,BUSY,BUT,BUY,BY,CABINE" ++
  "T,CALL,CAMPAIGN,CAN,CANDIDATE,CAPABLE,CAPACITY,CAPITAL,CAR,CARD,CARE,CAREER,CAREFUL,CAREFULLY,CARRY,CASE,CASH,CAT,CATCH," ++
  "CATEGORY,CAUSE,CELL,CENTRAL,CENTRE,CENTURY,CERTAIN,CERTAINLY,CHAIN,CHAIR,CHAIRMAN,CHALLENGE,CHANCE,CHANGE,CHANNEL,CHAPTE" ++
  "R,CHARACTER,CHARACTERISTIC,CHARGE,CHEAP,CHECK,CHEMICAL,CHIEF,CHILD,CHOICE,CHOOSE,CHURCH,CIRCLE,CIRCUMSTANCE,CITIZEN,CITY" ++
  ",CIVIL,CLAIM,CLASS,CLEAN,CLEAR,CLEARLY,CLIENT,CLIMB,CLOSE,CLOSELY,CLOTHES,CLUB,COAL,CODE,COFFEE,COLD,COLLEAGUE,COLLECT,C" ++
  "OLLECTION,COLLEGE,COLOUR,COMBINATION,COMBINE,COME,COMMENT,COMMERCIAL,COMMISSION,COMMIT,COMMITMENT,COMMITTEE,COMMON,COMMU" ++
  "NICATION,COMMUNITY,COMPANY,COMPARE,COMPARISON,COMPETITION,COMPLETE,COMPLETELY,COMPLEX,COMPONENT,COMPUTER,CONCENTRATE,CON" ++
  "CENTRATION,CONCEPT,CONCERN,CONCERNED,CONCLUDE,CONCLUSION,CONDITION,CONDUCT,CONFERENCE,CONFIDENCE,CONFIRM,CONFLICT,CONGRE" ++
  "SS,CONNECT,CONNECTION,CONSEQUENCE,CONSERVATIVE,CONSIDER,CONSIDERABLE,CONSIDERATION,CONSIST,CONSTANT,CONSTRUCTION,CONSUME" ++
  "R,CONTACT,CONTAIN,CONTENT,CONTEXT,CONTINUE,CONTRACT,CONTRAST,CONTRIBUTE,CONTRIBUTION,CONTROL,CONVENTION,CONVERSATION,COP" ++
  "Y,CORNER,CORPORATE,CORRECT,COS,COST,COULD,COUNCIL,COUNT,COUNTRY,COUNTY,COUPLE,COURSE,COURT,COVER,CREATE,CREATION,CREDIT," ++
  "CRIME,CRIMINAL,CRISIS,CRITERION,CRITICAL,CRITICISM,CROSS,CROWD,CRY,CULTURAL,CULTURE,CUP,CURRENT,CURRENTLY,CURRICULUM,CUS" ++
  "TOMER,CUT,DAMAGE,DANGER,DANGEROUS,DARK,DATA,DATE,DAUGHTER,DAY,DEAD,DEAL,DEATH,DEBATE,DEBT,DECADE,DECIDE,DECISION,DECLARE" ++
  ",DEEP,DEFENCE,DEFENDANT,DEFINE,DEFINITION,DEGREE,DELIVER,DEMAND,DEMOCRATIC,DEMONSTRATE,DENY,DEPARTMENT,DEPEND,DEPUTY,DER" ++
  "IVE,DESCRIBE,DESCRIPTION,DESIGN,DESIRE,DESK,DESPITE,DESTROY,DETAIL,DETAILED,DETERMINE,DEVELOP,DEVELOPMENT,DEVICE,DIE,DIF" ++
  "FERENCE,DIFFERENT,DIFFICULT,DIFFICULTY,DINNER,DIRECT,DIRECTION,DIRECTLY,DIRECTOR,DISAPPEAR,DISCIPLINE,DISCOVER,DISCUSS,D" ++
  "ISCUSSION,DISEASE,DISPLAY,DISTANCE,DISTINCTION,DISTRIBUTION,DISTRICT,DIVIDE,DIVISION,DO,DOCTOR,DOCUMENT,DOG,DOMESTIC,DOO" ++
  "R,DOUBLE,DOUBT,DOWN,DRAW,DRAWING,DREAM,DRESS,DRINK,DRIVE,DRIVER,DROP,DRUG,DRY,DUE,DURING,DUTY,EACH,EAR,EARLY,EARN,EARTH," ++
  "EASILY,EAST,EASY,EAT,ECONOMIC,ECONOMY,EDGE,EDITOR,EDUCATION,EDUCATIONAL,EFFECT,EFFECTIVE,EFFECTIVELY,EFFORT,EGG,EITHER,E" ++
  "LDERLY,ELECTION,ELEMENT,ELSE,ELSEWHERE,EMERGE,EMPHASIS,EMPLOY,EMPLOYEE,EMPLOYER,EMPLOYMENT,EMPTY,ENABLE,ENCOURAGE,END,EN" ++
  "EMY,ENERGY,ENGINE,ENGINEERING,ENJOY,ENOUGH,ENSURE,ENTER,ENTERPRISE,ENTIRE,ENTIRELY,ENTITLE,ENTRY,ENVIRONMENT,ENVIRONMENT" ++
  "AL,EQUAL,EQUALLY,EQUIPMENT,ERROR,ESCAPE,ESPECIALLY,ESSENTIAL,ESTABLISH,ESTABLISHMENT,ESTATE,ESTIMATE,EVEN,EVENING,EVENT," ++
  "EVENTUALLY,EVER,EVERY,EVERYBODY,EVERYONE,EVERYTHING,EVIDENCE,EXACTLY,EXAMINATION,EXAMINE,EXAMPLE,EXCELLENT,EXCEPT,EXCHAN" ++
  "GE,EXECUTIVE,EXERCISE,EXHIBITION,EXIST,EXISTENCE,EXISTING,EXPECT,EXPECTATION,EXPENDITURE,EXPENSE,EXPENSIVE,EXPERIENCE,EX" ++
  "PERIMENT,EXPERT,EXPLAIN,EXPLANATION,EXPLORE,EXPRESS,EXPRESSION,EXTEND,EXTENT,EXTERNAL,EXTRA,EXTREMELY,EYE,FACE,FACILITY," ++
  "FACT,FACTOR,FACTORY,FAIL,FAILURE,FAIR,FAIRLY,FAITH,FALL,FAMILIAR,FAMILY,FAMOUS,FAR,FARM,FARMER,FASHION,FAST,FATHER,FAVOU" ++
  "R,FEAR,FEATURE,FEE,FEEL,FEELING,FEMALE,FEW,FIELD,FIGHT,FIGURE,FILE,FILL,FILM,FINAL,FINALLY,FINANCE,FINANCIAL,FIND,FINDIN" ++
  "G,FINE,FINGER,FINISH,FIRE,FIRM,FIRST,FISH,FIT,FIX,FLAT,FLIGHT,FLOOR,FLOW,FLOWER,FLY,FOCUS,FOLLOW,FOLLOWING,FOOD,FOOT,FOO" ++
  "TBALL,FOR,FORCE,FOREIGN,FOREST,FORGET,FORM,FORMAL,FORMER,FORWARD,FOUNDATION,FREE,FREEDOM,FREQUENTLY,FRESH,FRIEND,FROM,FR" ++
  "ONT,FRUIT,FUEL,FULL,FULLY,FUNCTION,FUND,FUNNY,FURTHER,FUTURE,GAIN,GAME,GARDEN,GAS,GATE,GATHER,GENERAL,GENERALLY,GENERATE" ++
  ",GENERATION,GENTLEMAN,GET,GIRL,GIVE,GLASS,GO,GOAL,GOD,GOLD,GOOD,GOVERNMENT,GRANT,GREAT,GREEN,GREY,GROUND,GROUP,GROW,GROW" ++
  "ING,GROWTH,GUEST,GUIDE,GUN,HAIR,HALF,HALL,HAND,HANDLE,HANG,HAPPEN,HAPPY,HARD,HARDLY,HATE,HAVE,HE,HEAD,HEALTH,HEAR,HEART," ++
  "HEAT,HEAVY,HELL,HELP,HENCE,HER,HERE,HERSELF,HIDE,HIGH,HIGHLY,HILL,HIM,HIMSELF,HIS,HISTORICAL,HISTORY,HIT,HOLD,HOLE,HOLID" ++
  "AY,HOME,HOPE,HORSE,HOSPITAL,HOT,HOTEL,HOUR,HOUSE,HOUSEHOLD,HOUSING,HOW,HOWEVER,HUGE,HUMAN,HURT,HUSBAND,I,IDEA,IDENTIFY,I" ++
  "F,IGNORE,ILLUSTRATE,IMAGE,IMAGINE,IMMEDIATE,IMMEDIATELY,IMPACT,IMPLICATION,IMPLY,IMPORTANCE,IMPORTANT,IMPOSE,IMPOSSIBLE," ++
  "IMPRESSION,IMPROVE,IMPROVEMENT,IN,INCIDENT,INCLUDE,INCLUDING,INCOME,INCREASE,INCREASED,INCREASINGLY,INDEED,INDEPENDENT,I" ++
  "NDEX,INDICATE,INDIVIDUAL,INDUSTRIAL,INDUSTRY,INFLUENCE,INFORM,INFORMATION,INITIAL,INITIATIVE,INJURY,INSIDE,INSIST,INSTAN" ++
  "CE,INSTEAD,INSTITUTE,INSTITUTION,INSTRUCTION,INSTRUMENT,INSURANCE,INTEND,INTENTION,INTEREST,INTERESTED,INTERESTING,INTER" ++
  "NAL,INTERNATIONAL,INTERPRETATION,INTERVIEW,INTO,INTRODUCE,INTRODUCTION,INVESTIGATE,INVESTIGATION,INVESTMENT,INVITE,INVOL" ++
  "VE,IRON,IS,ISLAND,ISSUE,IT,ITEM,ITS,ITSELF,JOB,JOIN,JOINT,JOURNEY,JUDGE,JUMP,JUST,JUSTICE,KEEP,KEY,KID,KILL,KIND,KING,KI" ++
  "TCHEN,KNEE,KNOW,KNOWLEDGE,LABOUR,LACK,LADY,LAND,LANGUAGE,LARGE,LARGELY,LAST,LATE,LATER,LATTER,LAUGH,LAUNCH,LAW,LAWYER,LA" ++
  "Y,LEAD,LEADER,LEADERSHIP,LEADING,LEAF,LEAGUE,LEAN,LEARN,LEAST,LEAVE,LEFT,LEG,LEGAL,LEGISLATION,LENGTH,LESS,LET,LETTER,LE" ++
  "VEL,LIABILITY,LIBERAL,LIBRARY,LIE,LIFE,LIFT,LIGHT,LIKE,LIKELY,LIMIT,LIMITED,LINE,LINK,LIP,LIST,LISTEN,LITERATURE,LITTLE," ++
  "LIVE,LIVING,LOAN,LOCAL,LOCATION,LONG,LOOK,LORD,LOSE,LOSS,LOT,LOVE,LOVELY,LOW,LUNCH,MACHINE,MAGAZINE,MAIN,MAINLY,MAINTAIN" ++
  ",MAJOR,MAJORITY,MAKE,MALE,MAN,MANAGE,MANAGEMENT,MANAGER,MANNER,MANY,MAP,MARK,MARKET,MARRIAGE,MARRIED,MARRY,MASS,MASTER,M" ++
  "ATCH,MATERIAL,MATTER,MAY,MAYBE,ME,MEAL,MEAN,MEANING,MEANS,MEANWHILE,MEASURE,MECHANISM,MEDIA,MEDICAL,MEET,MEETING,MEMBER," ++
  "MEMBERSHIP,MEMORY,MENTAL,MENTION,MERELY,MESSAGE,METAL,METHOD,MIDDLE,MIGHT,MILE,MILITARY,MILK,MIND,MINE,MINISTER,MINISTRY" ++
  ",MINUTE,MISS,MISTAKE,MODEL,MODERN,MODULE,MOMENT,MONEY,MONTH,MORE,MORNING,MOST,MOTHER,MOTION,MOTOR,MOUNTAIN,MOUTH,MOVE,MO" ++
  "VEMENT,MUCH,MURDER,MUSEUM,MUSIC,MUST,MY,MYSELF,NAME,NARROW,NATION,NATIONAL,NATURAL,NATURE,NEAR,NEARLY,NECESSARILY,NECESS" ++
  "ARY,NECK,NEED,NEGOTIATION,NEIGHBOUR,NEITHER,NETWORK,NEVER,NEVERTHELESS,NEW,NEWS,NEWSPAPER,NEXT,NICE,NIGHT,NO,NOBODY,NOD," ++
  "NOISE,NONE,NOR,NORMAL,NORMALLY,NORTH,NORTHERN,NOSE,NOT,NOTE,NOTHING,NOTICE,NOTION,NOW,NUCLEAR,NUMBER,NURSE,OBJECT,OBJECT" ++
  "IVE,OBSERVATION,OBSERVE,OBTAIN,OBVIOUS,OBVIOUSLY,OCCASION,OCCUR,ODD,OF,OFF,OFFENCE,OFFER,OFFICE,OFFICER,OFFICIAL,OFTEN,O" ++
  "IL,OKAY,OLD,ON,ONCE,ONE,ONLY,ONTO,OPEN,OPERATE,OPERATION,OPINION,OPPORTUNITY,OPPOSITION,OPTION,OR,ORDER,ORDINARY,ORGANIS" ++
  "ATION,ORGANISE,ORGANIZATION,ORIGIN,ORIGINAL,OTHER,OTHERWISE,OUGHT,OUR,OURSELVES,OUT,OUTCOME,OUTPUT,OUTSIDE,OVER,OVERALL," ++
  "OWN,OWNER,PACKAGE,PAGE,PAIN,PAINT,PAINTING,PAIR,PANEL,PAPER,PARENT,PARK,PARLIAMENT,PART,PARTICULAR,PARTICULARLY,PARTLY,P" ++
  "ARTNER,PARTY,PASS,PASSAGE,PAST,PATH,PATIENT,PATTERN,PAY,PAYMENT,PEACE,PENSION,PEOPLE,PER,PERCENT,PERFECT,PERFORM,PERFORM" ++
  "ANCE,PERHAPS,PERIOD,PERMANENT,PERSON,PERSONAL,PERSUADE,PHASE,PHONE,PHOTOGRAPH,PHYSICAL,PICK,PICTURE,PIECE,PLACE,PLAN,PLA" ++
  "NNING,PLANT,PLASTIC,PLATE,PLAY,PLAYER,PLEASE,PLEASURE,PLENTY,PLUS,POCKET,POINT,POLICE,POLICY,POLITICAL,POLITICS,POOL,POO" ++
  "R,POPULAR,POPULATION,POSITION,POSITIVE,POSSIBILITY,POSSIBLE,POSSIBLY,POST,POTENTIAL,POUND,POWER,POWERFUL,PRACTICAL,PRACT" ++
  "ICE,PREFER,PREPARE,PRESENCE,PRESENT,PRESIDENT,PRESS,PRESSURE,PRETTY,PREVENT,PREVIOUS,PREVIOUSLY,PRICE,PRIMARY,PRIME,PRIN" ++
  "CIPLE,PRIORITY,PRISON,PRISONER,PRIVATE,PROBABLY,PROBLEM,PROCEDURE,PROCESS,PRODUCE,PRODUCT,PRODUCTION,PROFESSIONAL,PROFIT" ++
  ",PROGRAM,PROGRAMME,PROGRESS,PROJECT,PROMISE,PROMOTE,PROPER,PROPERLY,PROPERTY,PROPORTION,PROPOSE,PROPOSAL,PROSPECT,PROTEC" ++
  "T,PROTECTION,PROVE,PROVIDE,PROVIDED,PROVISION,PUB,PUBLIC,PUBLICATION,PUBLISH,PULL,PUPIL,PURPOSE,PUSH,PUT,QUALITY,QUARTER" ++
  ",QUESTION,QUICK,QUICKLY,QUIET,QUITE,RACE,RADIO,RAILWAY,RAIN,RAISE,RANGE,RAPIDLY,RARE,RATE,RATHER,REACH,REACTION,READ,REA" ++
  "DER,READING,READY,REAL,REALISE,REALITY,REALIZE,REALLY,REASON,REASONABLE,RECALL,RECEIVE,RECENT,RECENTLY,RECOGNISE,RECOGNI" ++
  "TION,RECOGNIZE,RECOMMEND,RECORD,RECOVER,RED,REDUCE,REDUCTION,REFER,REFERENCE,REFLECT,REFORM,REFUSE,REGARD,REGION,REGIONA" ++
  "L,REGULAR,REGULATION,REJECT,RELATE,RELATION,RELATIONSHIP,RELATIVE,RELATIVELY,RELEASE,RELEVANT,RELIEF,RELIGION,RELIGIOUS," ++
  "RELY,REMAIN,REMEMBER,REMIND,REMOVE,REPEAT,REPLACE,REPLY,REPORT,REPRESENT,REPRESENTATION,REPRESENTATIVE,REQUEST,REQUIRE,R" ++
  "EQUIREMENT,RESEARCH,RESOURCE,RESPECT,RESPOND,RESPONSE,RESPONSIBILITY,RESPONSIBLE,REST,RESTAURANT,RESULT,RETAIN,RETURN,RE" ++
  "VEAL,REVENUE,REVIEW,REVOLUTION,RICH,RIDE,RIGHT,RING,RISE,RISK,RIVER,ROAD,ROCK,ROLE,ROLL,ROOF,ROOM,ROUND,ROUTE,ROW,ROYAL," ++
  "RULE,RUN,RURAL,SAFE,SAFETY,SALE,SAME,SAMPLE,SATISFY,SAVE,SAY,SCALE,SCENE,SCHEME,SCHOOL,SCIENCE,SCIENTIFIC,SCIENTIST,SCOR" ++
  "E,SCREEN,SEA,SEARCH,SEASON,SEAT,SECOND,SECONDARY,SECRETARY,SECTION,SECTOR,SECURE,SECURITY,SEE,SEEK,SEEM,SELECT,SELECTION" ++
  ",SELL,SEND,SENIOR,SENSE,SENTENCE,SEPARATE,SEQUENCE,SERIES,SERIOUS,SERIOUSLY,SERVANT,SERVE,SERVICE,SESSION,SET,SETTLE,SET" ++
  "TLEMENT,SEVERAL,SEVERE,SEX,SEXUAL,SHAKE,SHALL,SHAPE,SHARE,SHE,SHEET,SHIP,SHOE,SHOOT,SHOP,SHORT,SHOT,SHOULD,SHOULDER,SHOU" ++
  "T,SHOW,SHUT,SIDE,SIGHT,SIGN,SIGNAL,SIGNIFICANCE,SIGNIFICANT,SILENCE,SIMILAR,SIMPLE,SIMPLY,SINCE,SING,SINGLE,SIR,SISTER,S" ++
  "IT,SITE,SITUATION,SIZE,SKILL,SKIN,SKY,SLEEP,SLIGHTLY,SLIP,SLOW,SLOWLY,SMALL,SMILE,SO,SOCIAL,SOCIETY,SOFT,SOFTWARE,SOIL,S" ++
  "OLDIER,SOLICITOR,SOLUTION,SOME,SOMEBODY,SOMEONE,SOMETHING,SOMETIMES,SOMEWHAT,SOMEWHERE,SON,SONG,SOON,SORRY,SORT,SOUND,SO" ++
  "URCE,SOUTH,SOUTHERN,SPACE,SPEAK,SPEAKER,SPECIAL,SPECIES,SPECIFIC,SPEECH,SPEED,SPEND,SPIRIT,SPORT,SPOT,SPREAD,SPRING,STAF" ++
  "F,STAGE,STAND,STANDARD,STAR,START,STATE,STATEMENT,STATION,STATUS,STAY,STEAL,STEP,STICK,STILL,STOCK,STONE,STOP,STORE,STOR" ++
  "Y,STRAIGHT,STRANGE,STRATEGY,STREET,STRENGTH,STRIKE,STRONG,STRONGLY,STRUCTURE,STUDENT,STUDIO,STUDY,STUFF,STYLE,SUBJECT,SU" ++
  "BSTANTIAL,SUCCEED,SUCCESS,SUCCESSFUL,SUCH,SUDDENLY,SUFFER,SUFFICIENT,SUGGEST,SUGGESTION,SUITABLE,SUM,SUMMER,SUN,SUPPLY,S" ++
  "UPPORT,SUPPOSE,SURE,SURELY,SURFACE,SURPRISE,SURROUND,SURVEY,SURVIVE,SWITCH,SYSTEM,TABLE,TAKE,TALK,TALL,TAPE,TARGET,TASK," ++
  "TAX,TEA,TEACH,TEACHER,TEACHING,TEAM,TEAR,TECHNICAL,TECHNIQUE,TECHNOLOGY,TELEPHONE,TELEVISION,TELL,TEMPERATURE,TEND,TERM," ++
  "TERMS,TERRIBLE,TEST,TEXT,THAN,THANK,THANKS,THAT,THE,THEATRE,THEIR,THEM,THEME,THEMSELVES,THEN,THEORY,THERE,THEREFORE,THES" ++
  "E,THEY,THIN,THING,THINK,THIS,THOSE,THOUGH,THOUGHT,THREAT,THREATEN,THROUGH,THROUGHOUT,THROW,THUS,TICKET,TIME,TINY,TITLE,T" ++
  "O,TODAY,TOGETHER,TOMORROW,TONE,TONIGHT,TOO,TOOL,TOOTH,TOP,TOTAL,TOTALLY,TOUCH,TOUR,TOWARDS,TOWN,TRACK,TRADE,TRADITION,TR" ++
  "ADITIONAL,TRAFFIC,TRAIN,TRAINING,TRANSFER,TRANSPORT,TRAVEL,TREAT,TREATMENT,TREATY,TREE,TREND,TRIAL,TRIP,TROOP,TROUBLE,TR" ++
  "UE,TRUST,TRUTH,TRY,TURN,TWICE,TYPE,TYPICAL,UNABLE,UNDER,UNDERSTAND,UNDERSTANDING,UNDERTAKE,UNEMPLOYMENT,UNFORTUNATELY,UN" ++
  "ION,UNIT,UNITED,UNIVERSITY,UNLESS,UNLIKELY,UNTIL,UP,UPON,UPPER,URBAN,US,USE,USED,USEFUL,USER,USUAL,USUALLY,VALUE,VARIATI" ++
  "ON,VARIETY,VARIOUS,VARY,VAST,VEHICLE,VERSION,VERY,VIA,VICTIM,VICTORY,VIDEO,VIEW,VILLAGE,VIOLENCE,VISION,VISIT,VISITOR,VI" ++
  "TAL,VOICE,VOLUME,VOTE,WAGE,WAIT,WALK,WALL,WANT,WAR,WARM,WARN,WASH,WATCH,WATER,WAVE,WAY,WE,WEAK,WEAPON,WEAR,WEATHER,WEEK," ++
  "WEEKEND,WEIGHT,WELCOME,WELFARE,WELL,WEST,WESTERN,WHAT,WHATEVER,WHEN,WHERE,WHEREAS,WHETHER,WHICH,WHILE,WHILST,WHITE,WHO,W" ++
  "HOLE,WHOM,WHOSE,WHY,WIDE,WIDELY,WIFE,WILD,WILL,WIN,WIND,WINDOW,WINE,WING,WINNER,WINTER,WISH,WITH,WITHDRAW,WITHIN,WITHOUT" ++
  ",WOMAN,WONDER,WONDERFUL,WOOD,WORD,WORK,WORKER,WORKING,WORKS,WORLD,WORRY,WORTH,WOULD,WRITE,WRITER,WRITING,WRONG,YARD,YEAH" ++
  ",YEAR,YES,YESTERDAY,YET,YOU,YOUNG,YOUR,YOURSELF,YOUTH"

partial def triangleNumbers (n : Nat) : List Nat :=
  (List.range n).map (fun k => (k + 1) * (k + 2) / 2)

partial def sqrtIfSquare (n : Nat) : Nat :=
  let rec loop (i : Nat) : Nat :=
    if i * i > n then 0 else if i * i == n then i else loop (i + 1)
  loop 1

partial def isTriangle (x : Nat) : Bool :=
  if x == 0 then
    false
  else
    let d := 1 + 8 * x
    let s := sqrtIfSquare d
    s != 0 && (s - 1) % 2 == 0

partial def wordValue (w : String) : Nat :=
  w.data.foldl (fun acc c => if c >= 'A' && c <= 'Z' then acc + (c.toNat - 'A'.toNat + 1) else acc) 0

partial def parseWords (s : String) : List String :=
  s.splitOn ","

partial def countTriangleWords (words : List String) : Nat :=
  words.foldl (fun acc w => if isTriangle (wordValue w) then acc + 1 else acc) 0

def sol : Nat :=
  let words := parseWords wordsText
  countTriangleWords words

example : triangleNumbers 10 = [1,3,6,10,15,21,28,36,45,55] := by
  native_decide

example : wordValue "SKY" = 55 := by
  native_decide

example : isTriangle 55 = true := by
  native_decide

end ProjectEulerSolutions.P42
open ProjectEulerSolutions.P42

def main : IO Unit := do
  IO.println sol

