= Project Euler Solvers
:docinfo:
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

This repo aims to solve ALL https://projecteuler.net[Project Euler] problems in openly licensed Python code, mostly using LLMs to generate the bulk of the solutions.

Tested on Python 3.13.7, PyPy 7.3.20, Ubuntu 25.10.

toc::[]

== Goals

There are a few solution collections out there such as https://github.com/nayuki/Project-Euler-solutions and https://github.com/stbrumme/euler but we couldn't find any complete ones, and the reason is obvious: no single human has the patience.

We also have https://github.com/lucky-bai/projecteuler-solutions which contains the numerical solutions. And of course, once you have the numerical solution you can enter the private forum threads where people freely share their solutions. But they don't use open licenses, so we can't republish them openly.

But with the advent of https://matharena.ai/?comp=euler--euler&task=4&model=GPT-5+%28high%29&view=problem&run=1[LLMs being able to solve a large number of them], this has become a possibility.

At least initially, we are not going to restrict ourselves only to LLM solutions, or attempt to carefully benchmark LLM performance with this repo. If one problem is hard and we manually find a solution, it is fine to add it manually. The initial goal is just to have all solvers with as little effort and money as possible.

The main reasons for creating this repo are:

* let people and LLMs get solutions without wasting more GPUs
* pissing off Project Euler people who say solutions must not be published
* beauty

== Setup

[source,shell]
----
virtualenv -p python3 .venv
. .venv/bin/activate
----

== Generating solvers

Try to generate solvers for problems 420 with the OpenAI API:

[source,shell]
----
./generate-solvers.py 420
----

Same but for problems 420 - 430:

[source,shell]
----
./generate-solvers.py 420 430
----

The program hangs until all tasks are done. This may take a while, 10-15 mins is common. If successful, solvers are stored under link:solvers[]

Same but in batch mode, which is much cheaper but may take up to 24 hours to complete:

[source,shell]
----
./generate-solvers.py --batch 420 430
----

== Testing

Run just one solver link:solvers/400.py[]:

[source,shell]
----
pypy3 solvers/400.py
----

Each solver should print the final solution to stdout and nothing else.

They should also assert any other given test values to increase the probability that the solver is actually correct.

Run all solvers and check for correctness against https://github.com/lucky-bai/projecteuler-solutions[projecteuler-solutions]:

[source,shell]
----
./test.py
----

Same for one specific solver:

[source,shell]
----
./test.py 400
----

Same for an inclusive range of solvers:

[source,shell]
----
./test.py 400-410
----

== Folders

* link:solvers/[]: the solver programs
** link:solvers/400.py[]: a solver program
** link:solvers/400.md[]: optional high level Markdown description of the solution
** link:solvers/400.json[]: optional LLM metadata describing the generation process

== License

* link:solvers/[]: https://creativecommons.org/public-domain/cc0/[CC0] (public domain), or whatever your lawyer says is the license for code generated by LLMs, or CC-By-NC-SA if your lawyer says that problem solutions must have the same license as problem statements

== Results

Benchmark on Lenovo ThinkPad P14s by running `./main.py`:

|===
| ID | time (s)
| 0 | 
| 1 | 0.074
| 400 | 0.342
| 401 | 2.009
| 402 | 0.127
| 403 | 1.094
| 404 | 9.342
| 405 | 0.083
| 406 | 1.002
| 407 | 8.929
| 408 | 2.705
| 409 | 0.329
| 410 | 1.995
| 411 | 13.880
| 412 | 0.578
| 413 | 18.845
| 414 | 13.126
| 420 | 0.982
| 910 | 39.422
| 948 | 0.191
| 949 | 
| 953 | 86.836
| 954 | 76.641
| 955 | 0.482
| 956 | 0.151
| 958 | 276.748
| 960 | 0.061
| 961 | 1.306
| 962 | 27.947
| 963 | 15.752
| 964 | 0.114
| 965 | 
| 967 | 1.591
| 968 | 0.932
| 969 | 0.065
| 970 | 0.125
| 971 | 3.249
| 972 | 50.921
| 973 | 0.423
| 974 | 0.320
|===
